issues:
  fix: true
  new-from-rev: master
linters:
  enable:
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - cyclop
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosmopolitan
  - grouper
  - importas
  - interfacebloat
  - loggercheck
  - maintidx
  - makezero
  - mirror
  - misspell
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - nlreturn
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - usestdlibvars
  - varnamelen
  - wastedassign
  - whitespace
  - wrapcheck
  - wsl
  - zerologlint

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel

  errcheck:
    exclude-functions:
      - github.com/go-chi/render.Render
