// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: ssh_key.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const SSHKeyAdd = `-- name: SSHKeyAdd :exec
insert into unweave.ssh_key (owner_id, name, public_key)
values ($1, $2, $3)
`

type SSHKeyAddParams struct {
	OwnerID   string `json:"ownerID"`
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"`
}

func (q *Queries) SSHKeyAdd(ctx context.Context, arg SSHKeyAddParams) error {
	_, err := q.db.ExecContext(ctx, SSHKeyAdd, arg.OwnerID, arg.Name, arg.PublicKey)
	return err
}

const SSHKeyGetByName = `-- name: SSHKeyGetByName :one
select id, name, owner_id, created_at, public_key, is_active
from unweave.ssh_key
where name = $1
  and owner_id = $2
`

type SSHKeyGetByNameParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"ownerID"`
}

func (q *Queries) SSHKeyGetByName(ctx context.Context, arg SSHKeyGetByNameParams) (UnweaveSshKey, error) {
	row := q.db.QueryRowContext(ctx, SSHKeyGetByName, arg.Name, arg.OwnerID)
	var i UnweaveSshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.PublicKey,
		&i.IsActive,
	)
	return i, err
}

const SSHKeyGetByPublicKey = `-- name: SSHKeyGetByPublicKey :one
select id, name, owner_id, created_at, public_key, is_active
from unweave.ssh_key
where public_key = $1
  and owner_id = $2
`

type SSHKeyGetByPublicKeyParams struct {
	PublicKey string `json:"publicKey"`
	OwnerID   string `json:"ownerID"`
}

func (q *Queries) SSHKeyGetByPublicKey(ctx context.Context, arg SSHKeyGetByPublicKeyParams) (UnweaveSshKey, error) {
	row := q.db.QueryRowContext(ctx, SSHKeyGetByPublicKey, arg.PublicKey, arg.OwnerID)
	var i UnweaveSshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.PublicKey,
		&i.IsActive,
	)
	return i, err
}

const SSHKeysGet = `-- name: SSHKeysGet :many
select id, name, owner_id, created_at, public_key, is_active
from unweave.ssh_key
where owner_id = $1
`

func (q *Queries) SSHKeysGet(ctx context.Context, ownerID string) ([]UnweaveSshKey, error) {
	rows, err := q.db.QueryContext(ctx, SSHKeysGet, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnweaveSshKey
	for rows.Next() {
		var i UnweaveSshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.PublicKey,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SSHKeysGetByIDs = `-- name: SSHKeysGetByIDs :many
SELECT id, name, owner_id, created_at, public_key, is_active
FROM unweave.ssh_key
WHERE id = ANY($1::text[])
`

func (q *Queries) SSHKeysGetByIDs(ctx context.Context, ids []string) ([]UnweaveSshKey, error) {
	rows, err := q.db.QueryContext(ctx, SSHKeysGetByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnweaveSshKey
	for rows.Next() {
		var i UnweaveSshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.PublicKey,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
